# name: Send Email Every 5 Minutes

# on:
#   schedule:
#     # - cron: "*/5 * * * *"  # every 5 minutes
#   workflow_dispatch:       # manual trigger button

# jobs:
#   send-email:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.10"

#       - name: Run Python email script
#         env:
#           SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
#           SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
#           RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
#         run: python send_email.py
